# Form implementation generated from reading ui file '/Users/nguyenthanhcong/PycharmProjects/tuduylaptrinh/LearnQLabel/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 569)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelname = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelname.setGeometry(QtCore.QRect(40, 0, 301, 61))
        self.labelname.setObjectName("labelname")
        self.pushButtonchangetext = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonchangetext.setGeometry(QtCore.QRect(30, 70, 121, 41))
        self.pushButtonchangetext.setObjectName("pushButtonchangetext")
        self.pushButtonfontsize = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonfontsize.setGeometry(QtCore.QRect(160, 70, 121, 41))
        self.pushButtonfontsize.setObjectName("pushButtonfontsize")
        self.pushButtonalignleft = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonalignleft.setGeometry(QtCore.QRect(340, 70, 121, 41))
        self.pushButtonalignleft.setObjectName("pushButtonalignleft")
        self.pushButtonaligncenter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonaligncenter.setGeometry(QtCore.QRect(480, 70, 121, 41))
        self.pushButtonaligncenter.setObjectName("pushButtonaligncenter")
        self.pushButtonalignright = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonalignright.setGeometry(QtCore.QRect(620, 70, 121, 41))
        self.pushButtonalignright.setObjectName("pushButtonalignright")
        self.pushButtonshowpng = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonshowpng.setGeometry(QtCore.QRect(170, 130, 201, 51))
        self.pushButtonshowpng.setObjectName("pushButtonshowpng")
        self.pushButtonshowgif = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonshowgif.setGeometry(QtCore.QRect(400, 130, 201, 51))
        self.pushButtonshowgif.setObjectName("pushButtonshowgif")
        self.imagelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagelabel.setGeometry(QtCore.QRect(80, 200, 631, 351))
        self.imagelabel.setText("")
        self.imagelabel.setPixmap(QtGui.QPixmap("/Users/nguyenthanhcong/PycharmProjects/tuduylaptrinh/LearnQLabel/images/hehe.png"))
        self.imagelabel.setScaledContents(True)
        self.imagelabel.setObjectName("imagelabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelname.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#e4a1ea;\">Nguyen Thanh Dang Khoa</span></p></body></html>"))
        self.pushButtonchangetext.setText(_translate("MainWindow", "Change Text"))
        self.pushButtonfontsize.setText(_translate("MainWindow", "Font Size ++"))
        self.pushButtonalignleft.setText(_translate("MainWindow", "Align Left"))
        self.pushButtonaligncenter.setText(_translate("MainWindow", "Align Center"))
        self.pushButtonalignright.setText(_translate("MainWindow", "Align Right"))
        self.pushButtonshowpng.setText(_translate("MainWindow", "Show  .PNG Format"))
        self.pushButtonshowgif.setText(_translate("MainWindow", "Show .GIF Format"))
