# Form implementation generated from reading ui file 'D:\UEL\hk1_2025_2026\tdlt\thuchanhtrenlop\thuethunhap\ui\ThueMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 170, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.lineEditSalary = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSalary.setGeometry(QtCore.QRect(40, 90, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditSalary.setFont(font)
        self.lineEditSalary.setObjectName("lineEditSalary")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 150, 271, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton2025 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton2025.setGeometry(QtCore.QRect(20, 20, 121, 21))
        self.radioButton2025.setObjectName("radioButton2025")
        self.radioButton2026 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton2026.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.radioButton2026.setObjectName("radioButton2026")
        self.pushButtonTinhThue = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTinhThue.setGeometry(QtCore.QRect(190, 250, 111, 21))
        self.pushButtonTinhThue.setObjectName("pushButtonTinhThue")
        self.lineEditThue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditThue.setGeometry(QtCore.QRect(50, 320, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditThue.setFont(font)
        self.lineEditThue.setText("")
        self.lineEditThue.setObjectName("lineEditThue")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 280, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TINH THUE THU NHAP CA NHAN"))
        self.label_2.setText(_translate("MainWindow", "NHAP LUONG CUA BAN:"))
        self.lineEditSalary.setText(_translate("MainWindow", "35000000"))
        self.groupBox.setTitle(_translate("MainWindow", "CHON PHUONG AN THUE"))
        self.radioButton2025.setText(_translate("MainWindow", "THEO NAM 2025"))
        self.radioButton2026.setText(_translate("MainWindow", "THEO NAM 2026"))
        self.pushButtonTinhThue.setText(_translate("MainWindow", "TINH THUE"))
        self.label_3.setText(_translate("MainWindow", "THUE PHAI NOP:"))
